export const ANIMAIONS = {
  Idle: "Idle",
  Death: "Death",
  Gun_Shoot: "Gun_Shoot",
  HitRecieve: "HitRecieve",
  HitRecieve_2: "HitRecieve_2",
  Idle_Gun: "Idle_Gun",
  Idle_Gun_Pointing: "Idle_Gun_Pointing",
  Idle_Gun_Shoot: "Idle_Gun_Shoot",
  Idle_Neutral: "Idle_Neutral",
  Idle_Sword: "Idle_Sword",
  Interact: "Interact",
  Kick_Left: "Kick_Left",
  Kick_Right: "Kick_Right",
  Punch_Left: "Punch_Left",
  Punch_Right: "Punch_Right",
  Roll: "Roll",
  Run: "Run",
  Run_Back: "Run_Back",
  Run_Left: "Run_Left",
  Run_Right: "Run_Right",
  Run_Shoot: "Run_Shoot",
  Sword_Slash: "Sword_Slash",
  Walk: "Walk",
  Wave: "Wave",
} as const;
